import csv
from pathlib import Path
from urllib.parse import quote_plus


ROOT = Path(__file__).resolve().parents[1]
OUTPUTS = [
    ROOT / "backend" / "data" / "products.csv",
    ROOT.parent / "product_recommender" / "products.csv",
]


FIELDS = [
    "product_id",
    "name",
    "brand",
    "category",
    "subcategory",
    "retailer",
    "affiliate_network",
    "price",
    "currency",
    "price_tier",
    "rating",
    "review_count",
    "targets",
    "active_ingredients",
    "skin_types",
    "avoid_if",
    "usage_time",
    "frequency",
    "priority",
    "in_stock",
    "country",
    "image_url",
    "product_url",
    "affiliate_url",
    "why",
]


def amazon_search(product_name: str) -> str:
    return f"https://www.amazon.com/s?k={quote_plus(product_name)}"


def sephora_search(product_name: str) -> str:
    return f"https://www.sephora.com/search?keyword={quote_plus(product_name)}"


def placeholder(label: str) -> str:
    return f"https://placehold.co/640x760/fdf2f8/8a2d4b?text={quote_plus(label)}"


rows = [
    {
        "product_id": "amazon_lrp_anthelios_spf60",
        "name": "La Roche-Posay Anthelios Melt-In Milk Sunscreen SPF 60",
        "brand": "La Roche-Posay",
        "category": "sunscreen",
        "subcategory": "face_body_spf",
        "retailer": "Amazon",
        "affiliate_network": "Amazon Associates",
        "price": "36.99",
        "currency": "USD",
        "price_tier": "$$",
        "rating": "4.6",
        "review_count": "12000",
        "targets": "pigmentation;redness;wrinkles;barrier",
        "active_ingredients": "spf;antioxidants",
        "skin_types": "all;sensitive",
        "avoid_if": "",
        "usage_time": "morning",
        "frequency": "daily",
        "priority": "100",
        "in_stock": "unknown",
        "country": "US",
        "image_url": placeholder("SPF"),
        "product_url": amazon_search("La Roche-Posay Anthelios Melt-In Milk Sunscreen SPF 60"),
        "affiliate_url": "REPLACE_WITH_AMAZON_ASSOCIATES_LINK",
        "why": "Daily sunscreen is essential when pigmentation or aging signs are detected.",
    },
    {
        "product_id": "sephora_supergoop_unseen_spf40",
        "name": "Supergoop! Unseen Sunscreen SPF 40",
        "brand": "Supergoop!",
        "category": "sunscreen",
        "subcategory": "face_spf",
        "retailer": "Sephora",
        "affiliate_network": "Sephora Rakuten or Skimlinks",
        "price": "38.00",
        "currency": "USD",
        "price_tier": "$$",
        "rating": "4.5",
        "review_count": "8000",
        "targets": "pigmentation;wrinkles;barrier",
        "active_ingredients": "spf",
        "skin_types": "all",
        "avoid_if": "",
        "usage_time": "morning",
        "frequency": "daily",
        "priority": "96",
        "in_stock": "unknown",
        "country": "US",
        "image_url": placeholder("SPF"),
        "product_url": sephora_search("Supergoop Unseen Sunscreen SPF 40"),
        "affiliate_url": "REPLACE_WITH_SEPHORA_AFFILIATE_LINK",
        "why": "Invisible daily SPF option for tone protection and photoaging prevention.",
    },
    {
        "product_id": "sephora_paulas_choice_bha2",
        "name": "Paula's Choice Skin Perfecting 2% BHA Liquid Exfoliant",
        "brand": "Paula's Choice",
        "category": "exfoliant",
        "subcategory": "bha",
        "retailer": "Sephora",
        "affiliate_network": "Sephora Rakuten or Skimlinks",
        "price": "35.00",
        "currency": "USD",
        "price_tier": "$$",
        "rating": "4.5",
        "review_count": "9000",
        "targets": "blackheads;pores;acne;texture",
        "active_ingredients": "salicylic acid;green tea",
        "skin_types": "oily;combination;normal",
        "avoid_if": "pregnancy;aspirin_allergy;very_sensitive",
        "usage_time": "evening",
        "frequency": "2-3x_week",
        "priority": "98",
        "in_stock": "unknown",
        "country": "US",
        "image_url": placeholder("BHA"),
        "product_url": sephora_search("Paula's Choice 2% BHA Liquid Exfoliant"),
        "affiliate_url": "REPLACE_WITH_SEPHORA_AFFILIATE_LINK",
        "why": "BHA is useful when pores blackheads or acne signals are high.",
    },
    {
        "product_id": "amazon_cerave_acne_control_gel",
        "name": "CeraVe Acne Control Gel",
        "brand": "CeraVe",
        "category": "treatment",
        "subcategory": "acne_treatment",
        "retailer": "Amazon",
        "affiliate_network": "Amazon Associates",
        "price": "19.99",
        "currency": "USD",
        "price_tier": "$",
        "rating": "4.5",
        "review_count": "5000",
        "targets": "acne;pores;blackheads",
        "active_ingredients": "salicylic acid;glycolic acid;lactic acid;niacinamide;ceramides",
        "skin_types": "oily;acne_prone",
        "avoid_if": "pregnancy;aspirin_allergy;very_sensitive",
        "usage_time": "evening",
        "frequency": "2-3x_week",
        "priority": "90",
        "in_stock": "unknown",
        "country": "US",
        "image_url": placeholder("Acne Gel"),
        "product_url": amazon_search("CeraVe Acne Control Gel"),
        "affiliate_url": "REPLACE_WITH_AMAZON_ASSOCIATES_LINK",
        "why": "Acne-focused option with salicylic acid and barrier-supporting ingredients.",
    },
    {
        "product_id": "amazon_cerave_resurfacing_retinol",
        "name": "CeraVe Resurfacing Retinol Serum",
        "brand": "CeraVe",
        "category": "retinoid",
        "subcategory": "retinol_serum",
        "retailer": "Amazon",
        "affiliate_network": "Amazon Associates",
        "price": "23.99",
        "currency": "USD",
        "price_tier": "$",
        "rating": "4.6",
        "review_count": "42000",
        "targets": "pigmentation;pores;wrinkles;acne_marks",
        "active_ingredients": "retinol;niacinamide;ceramides;licorice root",
        "skin_types": "normal;oily;combination",
        "avoid_if": "pregnancy;breastfeeding;very_sensitive",
        "usage_time": "evening",
        "frequency": "2-3x_week",
        "priority": "88",
        "in_stock": "unknown",
        "country": "US",
        "image_url": placeholder("Retinol"),
        "product_url": amazon_search("CeraVe Resurfacing Retinol Serum"),
        "affiliate_url": "REPLACE_WITH_AMAZON_ASSOCIATES_LINK",
        "why": "Retinol option for post-acne marks pores texture and early aging appearance.",
    },
    {
        "product_id": "sephora_ordinary_azelaic10",
        "name": "The Ordinary Azelaic Acid Suspension 10%",
        "brand": "The Ordinary",
        "category": "treatment",
        "subcategory": "azelaic_acid",
        "retailer": "Sephora",
        "affiliate_network": "Sephora Rakuten or Skimlinks",
        "price": "13.00",
        "currency": "USD",
        "price_tier": "$",
        "rating": "4.2",
        "review_count": "3000",
        "targets": "pigmentation;redness;acne",
        "active_ingredients": "azelaic acid",
        "skin_types": "all",
        "avoid_if": "very_sensitive",
        "usage_time": "evening",
        "frequency": "daily_or_alternate",
        "priority": "94",
        "in_stock": "unknown",
        "country": "US",
        "image_url": placeholder("Azelaic"),
        "product_url": sephora_search("The Ordinary Azelaic Acid Suspension 10%"),
        "affiliate_url": "REPLACE_WITH_SEPHORA_AFFILIATE_LINK",
        "why": "Targets uneven tone texture redness appearance and blemish-prone skin.",
    },
    {
        "product_id": "sephora_ordinary_niacinamide10",
        "name": "The Ordinary Niacinamide 10% + Zinc 1%",
        "brand": "The Ordinary",
        "category": "serum",
        "subcategory": "niacinamide",
        "retailer": "Sephora",
        "affiliate_network": "Sephora Rakuten or Skimlinks",
        "price": "6.00",
        "currency": "USD",
        "price_tier": "$",
        "rating": "4.3",
        "review_count": "10000",
        "targets": "pores;blackheads;acne;redness;barrier",
        "active_ingredients": "niacinamide;zinc pca",
        "skin_types": "all",
        "avoid_if": "niacinamide_sensitivity",
        "usage_time": "morning/evening",
        "frequency": "daily",
        "priority": "84",
        "in_stock": "unknown",
        "country": "US",
        "image_url": placeholder("Niacinamide"),
        "product_url": sephora_search("The Ordinary Niacinamide 10% Zinc 1%"),
        "affiliate_url": "REPLACE_WITH_SEPHORA_AFFILIATE_LINK",
        "why": "Supports brightness texture oil control and the appearance of pores.",
    },
    {
        "product_id": "amazon_lrp_toleriane_double_repair",
        "name": "La Roche-Posay Toleriane Double Repair Face Moisturizer",
        "brand": "La Roche-Posay",
        "category": "moisturizer",
        "subcategory": "face_moisturizer",
        "retailer": "Amazon",
        "affiliate_network": "Amazon Associates",
        "price": "23.99",
        "currency": "USD",
        "price_tier": "$",
        "rating": "4.6",
        "review_count": "30000",
        "targets": "barrier;redness;wrinkles",
        "active_ingredients": "ceramide-3;niacinamide;glycerin",
        "skin_types": "all;sensitive",
        "avoid_if": "",
        "usage_time": "morning/evening",
        "frequency": "daily",
        "priority": "78",
        "in_stock": "unknown",
        "country": "US",
        "image_url": placeholder("Moisturizer"),
        "product_url": amazon_search("La Roche-Posay Toleriane Double Repair Face Moisturizer"),
        "affiliate_url": "REPLACE_WITH_AMAZON_ASSOCIATES_LINK",
        "why": "Barrier-support moisturizer with niacinamide and ceramides.",
    },
    {
        "product_id": "amazon_cerave_hydrating_cleanser",
        "name": "CeraVe Hydrating Facial Cleanser",
        "brand": "CeraVe",
        "category": "cleanser",
        "subcategory": "gentle_cleanser",
        "retailer": "Amazon",
        "affiliate_network": "Amazon Associates",
        "price": "15.99",
        "currency": "USD",
        "price_tier": "$",
        "rating": "4.7",
        "review_count": "90000",
        "targets": "barrier;redness",
        "active_ingredients": "hyaluronic acid;ceramides",
        "skin_types": "normal;dry;sensitive",
        "avoid_if": "",
        "usage_time": "morning/evening",
        "frequency": "daily",
        "priority": "70",
        "in_stock": "unknown",
        "country": "US",
        "image_url": placeholder("Cleanser"),
        "product_url": amazon_search("CeraVe Hydrating Facial Cleanser"),
        "affiliate_url": "REPLACE_WITH_AMAZON_ASSOCIATES_LINK",
        "why": "Gentle cleanser for maintaining the skin barrier.",
    },
    {
        "product_id": "sephora_drunk_elephant_cfirma",
        "name": "Drunk Elephant C-Firma Fresh Day Serum",
        "brand": "Drunk Elephant",
        "category": "serum",
        "subcategory": "vitamin_c",
        "retailer": "Sephora",
        "affiliate_network": "Sephora Rakuten or Skimlinks",
        "price": "79.00",
        "currency": "USD",
        "price_tier": "$$$",
        "rating": "4.0",
        "review_count": "4000",
        "targets": "pigmentation;wrinkles;dullness",
        "active_ingredients": "vitamin c;ferulic acid;vitamin e",
        "skin_types": "normal;dry;combination",
        "avoid_if": "very_sensitive",
        "usage_time": "morning",
        "frequency": "daily",
        "priority": "76",
        "in_stock": "unknown",
        "country": "US",
        "image_url": placeholder("Vitamin C"),
        "product_url": sephora_search("Drunk Elephant C-Firma Fresh Day Serum"),
        "affiliate_url": "REPLACE_WITH_SEPHORA_AFFILIATE_LINK",
        "why": "Vitamin C option for brightness and uneven tone appearance.",
    },
]


for output in OUTPUTS:
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(rows)
    print(output)
